### ISSUE TITLE
Add support for groups of arguments.

### ISSUE THREAD

**Issue by Kentzo** [datafolklabs/cement#205]
Argparse supports grouping of arguments for better help message so cement should.

Current workaround is to override `_process_arguments`

**Comment by derks** [comment]
I have finally (finally!) put a lot of time into refactoring `CementBaseController` to use `Argparse` in a more natural way.  Currently, this work lives in a feature branch called `argument_handling` and would love some feedback on it if any of you all have time.

Essentially, this has completely reworked how commands and arguments are collected from controllers and passed to Argparse.  There are a number of features including:

**Processing of All Arguments, From All Controllers**

The current way with `CementBaseController` looks like:

```
$ myapp [sub-command] {options}

$ myapp [nested-controller] [sub-command] {options}

$ myapp [nested-controller] [nested-controller] [sub-command] {options}
```

The final/last controller would have to have all the arguments attached to it, and you can not pass options to any of the previously parsed namespaces.  That said, the new way looks like:

```
$ myapp {options}

$ myapp {options} [sub-command] {options}

$ myapp {options} [nested-controller] {options} [sub-command] {options}
```

For example:

```
$ myapp third --third-foo "3" command-3 -C "KAPLA"
Inside Third.command_3()
Got Big C Option > KAPLA
Got Third Foo Option > 3
```

**Controller Arguments vs. Command Arguments**

With `ArgparseController` we now have the ability to add additional arguments to the sub-command and controller separates.  For example:

```python
from cement.ext.ext_argparse import ArgparseController, expose

class MyController(ArgparseController):
    class Meta:
        label = 'my_controller'
        arguments = [
           ( ['-f', '--foo'], dict(help='foo option help') ),
        ]

    @expose(
        arguments=[
            ( ['--other-foo'], dict(help='option under my-sub-command) ),
        ],
        help='my-sub-command help',
        # other options passed directly to argparse
    )
    def my_sub_command(self):
        if self.app.pargs.other_foo:
            print('Received Other Foo Option > %s' % self.app.pargs.other_foo)

```

Essentially, all `**kw` passed to `@expose` will be handled off to `Argparse`, give flexibility to how arguments are handled (controller level vs. comand level).

**Working CementApp Example**
```python

from cement.core.foundation import CementApp
from cement.ext.ext_argparse import ArgparseController, expose

class Base(ArgparseController):
    class Meta:
        label = 'base'
        description = 'MyApp Does Amazing Things'
        arguments = [
            ( ['-f', '--foo'], dict(help='the notorious foo option')),
            ]

    @expose(hide=True)
    def default(self):
        print("Inside Base.default()")

    @expose(help='command-1 help message')
    def command_1(self):
        print("Inside Base.command_1()")

    def _process_parsed_arguments(self):
        if hasattr(self.app.pargs, 'foo') and self.app.pargs.foo:
            print('Got Foo Option > %s' % self.app.pargs.foo)

class Second(ArgparseController):
    class Meta:
        label = 'second'
        stacked_on = 'base'
        stacked_type = 'embedded'
        arguments = [
            (['--second-foo'], dict(help='second foo option')),
            ]

    @expose(help='command-2 help message')
    def command_2(self):
        print("Inside Second.command_2()")

class Third(ArgparseController):
    class Meta:
        label = 'third'
        stacked_on = 'base'
        stacked_type = 'nested'
        arguments = [
            (['--third-foo'], dict(help='third foo option', dest='third_foo')),
            ]

    @expose(
        arguments=[
            (['-C'], dict(help='the big C option', dest='big_c'))
            ],
        help='command-3 help message', 
        )
    def command_3(self):
        print("Inside Third.command_3()")

        if self.app.pargs.big_c:
            print('Got Big C Option > %s' % self.app.pargs.big_c)

    @expose(hide=True, help='asfasfasdf')
    def default(self):
        print("Inside Third.default()")

    def _process_parsed_arguments(self):
        if hasattr(self.app.pargs, 'third_foo') and self.app.pargs.third_foo:
            print('Got Third Foo Option > %s' % self.app.pargs.third_foo)


class MyAppApp(CementApp):
    class Meta:
        label = 'myapp'
        handlers = [Base, Second, Third]

def main():
    with MyAppApp() as app:
        app.run()

if __name__ == '__main__':
    main()
```

Looks like:

```
usage: myapp [-h] [--debug] [--quiet] [-f FOO] [--second-foo SECOND_FOO]
             {third,command-1,default,command-2} ...

optional arguments:
  -h, --help            show this help message and exit
  --debug               toggle debug output
  --quiet               suppress all output
  -f FOO, --foo FOO     the notorious foo option
  --second-foo SECOND_FOO
                        second foo option

sub-commands:
  {third,command-1,default,command-2}
    third               third controller
    command-1           command-1 help message
    command-2           command-2 help message

$ python myapp.py
Inside Base.default()

$ python myapp.py -f foo-1 command-1
Inside Base.command_1()
Got Foo Option > foo-1

$ python myapp.py -f foo-1 third --third-foo foo-3 command-3 -C KAPLA
Got Foo Option > foo-1
Got Third Foo Option > foo-3
Inside Third.command_3()
Got Big C Option > KAPLA
```

Note: Only testing on Python 3.

**Comment by dano** [comment]
@derks I actually just came to the tracker to request the ability to provide command-specific arguments. I'll take the `argument_handling` branch for a spin in the next couple of days and let you know how it goes.

**Comment by derks** [comment]
Thanks @dano! Let me know what you think... any feedback is appreciated.

**Comment by derks** [comment]
Note to self, this section can probably be refactored:

 * https://github.com/datafolklabs/cement/blob/argument_handling/cement/ext/ext_argparse.py#L411

`self._controllers` already resolved nesting/embedding order which (I believe) eliminates the need for all the whacky shit because `self._controllers` should be iterable in its current order.

**Comment by dano** [comment]
@derks I'm hitting errors when I try to use your test script (using Python 3.4):

```
dan@dan-002:~$ python3 myapp.py
Inside Base.default()
dan@dan002:~$ python3 myapp.py -f foo-1 command-1
Traceback (most recent call last):
  File "myapp.py", line 78, in <module>
    main()
  File "myapp.py", line 75, in main
    app.run()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.7.1.dev20150602060238-py3.4.egg/cement/core/foundation.py", line 764, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.7.1.dev20150602060238-py3.4.egg/cement/ext/ext_argparse.py", line 596, in _dispatch
    self.app._parse_args()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.7.1.dev20150602060238-py3.4.egg/cement/core/foundation.py", line 975, in _parse_args
    self._parsed_args = self.args.parse(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.7.1.dev20150602060238-py3.4.egg/cement/ext/ext_argparse.py", line 55, in parse
    return self.parse_args(arg_list)
  File "/usr/lib/python3.4/argparse.py", line 1737, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1769, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1978, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib/python3.4/argparse.py", line 1934, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.4/argparse.py", line 1843, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.4/argparse.py", line 1138, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib/python3.4/argparse.py", line 1769, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1978, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib/python3.4/argparse.py", line 1934, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.4/argparse.py", line 1843, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.7.1.dev20150602060238-py3.4.egg/cement/ext/ext_argparse.py", line 523, in __call__
    func_name = _clean_command_func(namespace.command)
AttributeError: 'Namespace' object has no attribute 'command'
```

**Comment by derks** [comment]
@dano Can I see your code?

**Comment by dano** [comment]
@derks I'm just running your "Working CementApp Example"` without any changes. I pulled down the `argument_handling` branch this morning and installed that. If it's working for you, I'm not sure what the issue might be...

**Comment by derks** [comment]
@dano Thanks... let me try it out again.

**Comment by derks** [comment]
Verified on Python 3.4.x ... doesn't have this issue on Python 3.3.x.  Will hopefully push a fix shortly.

**Comment by dano** [comment]
@derks I had a feeling that was the cause...thanks for the quick triage!

**Comment by derks** [comment]
@dano I've pushed up some changes to the `argument_handling` branch.  Tested on Python 2.7, 3.2, and 3.4.  Unfortunately, due to how Python <3.4 (Argparse) handles sub-parsers, this changes loses the 'default' command functionality.  Not sure if it will be possible to get that back or not but will continue to work on it.

Please let me know how things go testing that with Python 3.4.

```
$ python -V
Python 3.4.3

$ python myapp.py --foo bar third command-3 -C asfas
Got Foo Option > bar
Inside Third.command_3()
Got Big C Option > asfas
```

**Comment by dano** [comment]
@derks Thanks, that fixed it.

**Comment by derks** [comment]
I have been reading more up on argument groups in Argparse, and though this new controller does not directly interact with that it does provide the means to do so.

```python

from cement.ext.ext_argparse import ArgparseController, expose

class MyController(ArgparseController):
    class Meta:
        label = 'base'

        # add simple argument the same old way
        arguments = [
            (['-f', '--foo'], dict(help='my foo option', dest='foo'),
        ]

    def _pre_argument_parsing(self):
        group1 = self.parser.add_argument_group('my-special-group')
        group1.add_argument('--g1', help='my g1 option under my-special-group', dest='g1')
        group1.add_argument('--g2', help='my g2 option under my-special-group', dest='g2')

        # or mutually exclusive groups
        meg = self.parser.add_mutually_exclusive_group()
        meg.add_argument('--g3', help='my g3 option')
        meg.add_argument('--g4', help='my g4 option')
```

The above is untested example, but essentially in `_pre_argument_parsing` you can have full access to the sub parser for that controller... and do anything you would normally do with Argparse.

That said, there is currently no way to do this with controller sub-command arguments.  in the future, it would be nice to have the framework support groups better, but this will atleast make it possible.

**Comment by barta0** [comment]
In `Cement 2.6.2` I use the following workaround in the case of mutex groups:

```python
class FooController(CementBaseController):

    class Meta:
        label = 'foo'
        stacked_on = 'base'
        stacked_type = 'nested'
        mutex_groups = [
            {
                'required': True, # or False
                'arguments': [
                    (['--option1'], dict(action='store_true')),
                    (['--option2'], dict(action='store_true'))
                ]
            },
        ]

    @expose(hide=True)
    def default(self):
        pass
```
As you can see I added a `mutex_groups` property to `FooController.Meta` and I define mutex groups in a similar way, as we define arguments in Cement. 

This property is processed by this function:
```python
def set_mutex_groups_hook(app):
    if hasattr(app.controller._dispatch_command['controller'].Meta, 'mutex_groups'):
        for group in app.controller._dispatch_command['controller'].Meta.mutex_groups:
            mutex_group = app.args.add_mutually_exclusive_group(required=group['required'])

            for argument in group['arguments']:
                mutex_group.add_argument(argument[0][0], **argument[1])
```
This function is registered as a `pre_argument_parsing`hook. It access the `app.args `which is an `argparse.ArgumentParser` instance and creates the defined mutex groups.
