### ISSUE TITLE
default locale setting

### ISSUE THREAD

**Issue by harshadyeola** [datafolklabs/cement#295]
Is there any way that i can set default locale for may app to run without encoding issues?

**Comment by derks** [comment]
Can you elaborate on what you're looking for?  What encoding issues are you experiencing?

**Comment by harshadyeola** [comment]
@derks 
Actually, My application is facing encoding  problems. It supports utf-8 format. but anybody runs application on system having ascii encoding set as default it throws errors  with encoding.

So my question is, How should i set default encoding for my application so that it is independent of system default encoding format?

**Comment by gau1991** [comment]
Same happened when I was parsing mustache template:

My Code portion is this:
```
data = dict(salt=vm_salt)
ee_vmb = open('application.ini', encoding='utf-8', mode='w')
self.app.render((data), 'vimbadmin.mustache', out=ee_vmb)
ee_vmb.close()
```

When Cement reads my mustache template, it throws encoding error.

Got this error:
```
2015-02-17 11:49:43,222 (DEBUG) cement.core.output : attemping to load output template from file /usr/lib/ee/templates/vimbadmin.mustache
'ascii' codec can't decode byte 0xc2 in position 72: ordinal not in range(128)
2015-02-17 11:49:43,224 (DEBUG) cement.core.foundation : closing the application
```

Is there any way in Cement to define Encoding error while reading template file?

**Comment by derks** [comment]
Can you paste the `vimbadmin.mustache` template, or another template that would throw this error?

**Comment by gau1991** [comment]
@derks ,
This is my complete code:
```
from cement.core.foundation import CementApp
from cement.core.controller import CementBaseController, expose


class MyBaseController(CementBaseController):
    class Meta:
        label = 'base'
        description = 'MyApp Does Amazing Things'

    @expose(hide=True)
    def default(self):
        data = dict(salt="123456", host="localhost",password="password",php_user="www-data")
        ee_vmb = open('my.ini', encoding='utf-8', mode='w')
        self.app.render(data, 'vimbadmin.mustache', out=ee_vmb)
        ee_vmb.close()
        

class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        base_controller = MyBaseController
        extensions = ['mustache']
        template_dirs = ['~/']

        # default output handler
        output_handler = 'mustache'


app = MyApp()
try:
    app.setup()
    app.run()
finally:
    app.close()
```

You can download vimbadmin.mustache from [here](https://raw.githubusercontent.com/rtCamp/easyengine/python/ee/cli/templates/vimbadmin.mustache)

**Comment by derks** [comment]
I assume you are using Python 3 based on the use of `encoding="utf-8"` as a parameter to `open()` (not supported on Python 2.7)?  I've tested the above code with the `vimbadmin.mustache` template and did not receive any encoding errors.  My system:

 * MAC OSX 10.10.2
 * Python 3.3.1 (Installed via Brew)
 * Cement Master Branch


I am certain we can resolve whatever issues you are experiencing, but I need to be able to reproduce it first.  Please let me know any other details that might help reproduce the encoding issues you are experiencing.

Thank you!

**Comment by gau1991** [comment]
Hi @derks ,
Thanks for response.
Following is my system configuration:
- Ubuntu 14.04 x86_64
- Python 3.4.0 
- Cement stable 2.4.0
 
In our application (EasyEngine) some of our users are facing encoding issue. We can not tell each user to set locale to `en_US.UTF-8` on their system, so we are trying to make application independent of system locale.

On Linux based system we are able to reproduce this bug doing following:

```
root@vagrant-ubuntu-trusty-64:~# unset LANG
root@vagrant-ubuntu-trusty-64:~# python3 app.py 
Traceback (most recent call last):
  File "app.py", line 32, in <module>
    app.run()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "app.py", line 14, in default
    self.app.render(data, 'vimbadmin.mustache', out=ee_vmb)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/foundation.py", line 747, in render
    out_text = self.output.render(data, template)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/ext/ext_mustache.py", line 91, in render
    content = self.load_template(template)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/output.py", line 175, in load_template
    content = self._load_template_from_file(template_path)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/output.py", line 119, in _load_template_from_file
    content = open(full_path, 'r').read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 72: ordinal not in range(128)
```

**Comment by derks** [comment]
Very helpful. I will look at this further today.

**Comment by derks** [comment]
I was able to reproduce the issue using the above info on Ubuntu 14.04/Python 3.4.  I would like to implement something into Cement to handle this better, however in the meantime... with regards to the Mustache templates...  the following is a work-around.

```python

import os
from cement.core.foundation import CementApp
from cement.core.controller import CementBaseController, expose
from cement.utils import fs
from cement.ext.ext_mustache import MustacheOutputHandler


class MyOutputHandler(MustacheOutputHandler):
    class Meta:
        label = 'my_output_handler'

    def _load_template_from_file(self, path):
        for templ_dir in self.app._meta.template_dirs:
            full_path = fs.abspath(os.path.join(templ_dir, path))
            if os.path.exists(full_path):
                self.app.log.debug('loading template file %s' % full_path)
                return open(full_path, encoding='utf-8', mode='r').read()
            else:
                continue


class MyBaseController(CementBaseController):
    class Meta:
        label = 'base'
        description = 'MyApp Does Amazing Things'

    @expose(hide=True)
    def default(self):
        data = dict(salt="123456", host="localhost",password="password",php_user="www-data")
        ee_vmb = open('my.ini', encoding='utf-8', mode='w')
        self.app.render(data, 'vimbadmin.mustache', out=ee_vmb)
        ee_vmb.close()


class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        base_controller = MyBaseController
        extensions = ['mustache']
        template_dirs = ['~/']

        # default output handler
        output_handler = MyOutputHandler


app = MyApp()
app.setup()
app.run()
app.close()
```


Essentially, sub-classing the `MustacheOutputHandler` to workaround the loading of the template.  Obviously, there are other areas of the framework that might have the same issue... but hopefully this helps.

I am going to slate this for Cement 2.6.x to implement something, most likely `CementApp.Meta.encoding` that would be used wherever applicable.

**Comment by gau1991** [comment]
@derks Thanks for response..
That solutions working perfectly :+1: 
> I am going to slate this for Cement 2.6.x to implement something, most likely CementApp.Meta.encoding that would be used wherever applicable.

+1 for this.

**Comment by dploeger** [comment]
I had the same problem and solved it using a post_render-hook:

```python
# in App/Meta
hooks = [
            ("post_render", encode_output)
        ]

# (...)
def encode_output(app, text):

    """ Encode the output to be suitable for the terminal

    :param app: The Cement App (unused)
    :param text: The rendered text
    :return: The encoded text
    """

    return text.encode("utf-8")
```

**Comment by derks** [comment]
@dploeger excellent solution!  Didn't even think of going that route.

**Comment by derks** [comment]
Closing as part of the Cement 3.x modernization and backlog triage — this one is being closed due to inactivity and/or lack of current maintainer interest, not because it lacks merit.

If this is still a real issue or a desired feature against the latest Cement 3.0 release, please file a new issue rather than re-opening this one — a fresh report against current Cement will get attention much faster than reviving an aged thread.
