### ISSUE TITLE
Error creating app from boss template

### ISSUE THREAD

**Issue by fxstein** [datafolklabs/cement#298]
When following the tutorial and create a cement app from a boss tutorial I am getting the following error:

    boss create ./myapp -t boss:cement-app
    Traceback (most recent call last):
    File "/usr/local/bin/boss", line 9, in <module>
    load_entry_point('boss==0.9.16.dev20150224023836', 'console_scripts', 'boss')()
    File "/usr/local/lib/python3.4/site-packages/boss/cli/main.py", line 54, in main
    app.run()
    File "/usr/local/lib/python3.4/site-packages/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
    File "/usr/local/lib/python3.4/site-packages/cement/core/controller.py", line 461, in _dispatch
    return func()
    File "/usr/local/lib/python3.4/site-packages/boss/cli/controllers/base.py", line 71, in create
    src.create_from_template(source, template, self.app.pargs.extra[0])
    File "/usr/local/lib/python3.4/site-packages/boss/cli/source.py", line 63, in create_from_template
    tmpl.copy(dest_dir)
    File "/usr/local/lib/python3.4/site-packages/boss/cli/template.py", line 252, in copy
    self._populate_vars()
    File "/usr/local/lib/python3.4/site-packages/boss/cli/template.py", line 98, in _populate_vars
    res = raw_input("%s: " % question)
    NameError: name 'raw_input' is not defined

**Comment by derks** [comment]
Thanks!  This is actually a bug in Boss, and not Cement.  I'm moving the bug report to that repo... which you can track here:

 * https://github.com/datafolklabs/boss/issues/22

**Comment by fxstein** [comment]
My bad. Should have realized! Thank you!
