### ISSUE TITLE
ConfigHandler Config Defaults Broken

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#388]
Unable to merge config defaults in while setting up a config handler, because the config handler isn't setup yet:

```
2016-07-07 15:29:35,345 (DEBUG) cement.core.handler : merging config defaults from '<cement.ext.ext_json.JsonConfigHandler object at 0x109481908>' into section 'config.json'
Traceback (most recent call last):
  File "/Users/derks/.env/cement/bin/myapp2", line 9, in <module>
    load_entry_point('myapp2==0.9.1', 'console_scripts', 'myapp2')()
  File "/Users/derks/Development/cement/tmp/myapp2/myapp2/cli/main.py", line 63, in main
    with app:
  File "/Users/derks/Development/cement/cement/core/foundation.py", line 1387, in __enter__
    self.setup()
  File "/Users/derks/Development/cement/cement/core/foundation.py", line 778, in setup
    self._setup_config_handler()
  File "/Users/derks/Development/cement/cement/core/foundation.py", line 1131, in _setup_config_handler
    self._meta.config_handler)
  File "/Users/derks/Development/cement/cement/core/foundation.py", line 1118, in _resolve_handler
    han._setup(self)
  File "/Users/derks/Development/cement/cement/core/handler.py", line 365, in _setup
    self.app.config.merge(dict_obj, override=False)
AttributeError: 'NoneType' object has no attribute 'merge'
```

**Comment by derks** [comment]
The way things are now, it is not possible for a config handler to have config defaults, because it is the handler that handles processing config defaults (and it's not setup yet in the process).  Chicken and egg type thing...
