### ISSUE TITLE
Can't get user in daemon extension

### ISSUE THREAD

**Issue by qs** [datafolklabs/cement#401]
Example code from here http://cement.readthedocs.io/en/latest/api/ext/ext_daemon/#usage doesn't work form python2 on ubuntu 14.04

Running from CLI:

```
Traceback (most recent call last):
  File "runner.py", line 65, in <module>
    with MyApp() as app:
  File "/usr/local/lib/python2.7/dist-packages/cement/core/foundation.py", line 1494, in __enter__
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/foundation.py", line 860, in setup
    for res in self.hook.run('post_setup', self):
  File "/usr/local/lib/python2.7/dist-packages/cement/core/hook.py", line 150, in run
    res = hook[2](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cement/ext/ext_daemon.py", line 377, in extend_app
    user = pwd.getpwnam(os.getlogin())
OSError: [Errno 2] No such file or directory
```

Running from PyCharm:

```
Traceback (most recent call last):
  File "runner.py", line 65, in <module>
    with MyApp() as app:
  File "/usr/local/lib/python2.7/dist-packages/cement/core/foundation.py", line 1494, in __enter__
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/foundation.py", line 860, in setup
    for res in self.hook.run('post_setup', self):
  File "/usr/local/lib/python2.7/dist-packages/cement/core/hook.py", line 150, in run
    res = hook[2](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cement/ext/ext_daemon.py", line 377, in extend_app
    user = pwd.getpwnam(os.getlogin())
OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by derks** [comment]
I ran into this issue last week, but hadn't had a chance to work on it.  It's hit others aswell:

 * https://github.com/gitpython-developers/gitpython/issues/39


The pull request is exactly the direction I was going to go with it, so thank you for that!  I'm traveling this week, but will work on pushing this out to stable branch next week.
