### ISSUE TITLE
FrameworkError When Reusing CementApp Object

### ISSUE THREAD

**Issue by akhilman** [datafolklabs/cement#415]
I'm writing unittests and got hit by this behaviour:

```python
from cement.core.foundation import CementApp


def pre_setup(app):

    app.extend('object', object)


class BugyApp(CementApp):

    class Meta:

        label = 'bugy'

        hooks = [
            ('pre_setup', pre_setup),
        ]


# in case of unittests app is provided by CementTestCase
app = BugyApp()

# first app initialisation
with app:

    print(app.object)

# re-initialisation to check state loading
with app:

    print(app.object)

```
Executing this code will raise:
```
<class 'object'>
Traceback (most recent call last):
  File "extend_fault.py", line 28, in <module>
    with app:
  File "/home/ildar/projects/slivoglot-1/cement/cement/core/foundation.py", line 1494, in __enter__
    self.setup()
  File "/home/ildar/projects/slivoglot-1/cement/cement/core/foundation.py", line 843, in setup
    for res in self.hook.run('pre_setup', self):
  File "/home/ildar/projects/slivoglot-1/cement/cement/core/hook.py", line 150, in run
    res = hook[2](*args, **kwargs)
  File "extend_fault.py", line 6, in pre_setup
    app.extend('object', object)
  File "/home/ildar/projects/slivoglot-1/cement/cement/core/foundation.py", line 793, in extend
    member_name)
cement.core.exc.FrameworkError: App member 'object' already exists!
```
Second app initialisation tries to extend already extended app with `object` member.

**Comment by derks** [comment]
Thanks @akhilman!
