### ISSUE TITLE
Unable to run an example - Python3 & pylibmc

### ISSUE THREAD

**Issue by julenpardo** [datafolklabs/cement#425]
Hello,

I've noticed that there was an issue (#343) possibly related what with I'm currently facing. But as I'm unable to make it run, I open another issue.

These are the steps I've followed:

I create a virtual environment:

```
virtualenv --no-site-packages -p /usr/bin/python3 env/
source env/bin/activate
```
I install cement:
```
pip install cement
```

Output of `pip freeze`:

```
appdirs==1.4.0
cement==2.10.2
packaging==16.8
pkg-resources==0.0.0
pyparsing==2.1.10
six==1.10.0
```

I create create a script as in the [Quickstart section from the tutorial](http://builtoncement.com/2.10/dev/quickstart.html#getting-warmer):

```python
from cement.core.foundation import CementApp
from cement.core import hook
from cement.utils.misc import init_defaults

# define our default configuration options
defaults = init_defaults('myapp')
defaults['myapp']['debug'] = False
defaults['myapp']['some_param'] = 'some value'

# define any hook functions here
def my_cleanup_hook(app):
    pass

# define the application class
class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        config_defaults = defaults
        extensions = ['daemon', 'memcached', 'json', 'yaml']
        hooks = [
            ('pre_close', my_cleanup_hook),
        ]

with MyApp() as app:
    # add arguments to the parser
    app.args.add_argument('-f', '--foo', action='store', metavar='STR',
                          help='the notorious foo option')

    # log stuff
    app.log.debug("About to run my myapp application!")

    # run the application
    app.run()

    # continue with additional application logic
    if app.pargs.foo:
        app.log.info("Received option: foo => %s" % app.pargs.foo)
```

I try to execute:

```
python3 myapp.py
```

And I get:

```
Traceback (most recent call last):
  File "/home/julen/Desktop/cement-example/env/lib/python3.5/site-packages/cement/core/extension.py", line 145, in load_extension
    __import__(ext_module, globals(), locals(), [], 0)
  File "/home/julen/Desktop/cement-example/env/lib/python3.5/site-packages/cement/ext/ext_memcached.py", line 101, in <module>
    import pylibmc
ImportError: No module named 'pylibmc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myapp.py", line 24, in <module>
    with MyApp() as app:
  File "/home/julen/Desktop/cement-example/env/lib/python3.5/site-packages/cement/core/foundation.py", line 1494, in __enter__
    self.setup()
  File "/home/julen/Desktop/cement-example/env/lib/python3.5/site-packages/cement/core/foundation.py", line 846, in setup
    self._setup_extension_handler()
  File "/home/julen/Desktop/cement-example/env/lib/python3.5/site-packages/cement/core/foundation.py", line 1219, in _setup_extension_handler
    self.ext.load_extensions(self._meta.extensions)
  File "/home/julen/Desktop/cement-example/env/lib/python3.5/site-packages/cement/core/extension.py", line 166, in load_extensions
    self.load_extension(ext)
  File "/home/julen/Desktop/cement-example/env/lib/python3.5/site-packages/cement/core/extension.py", line 154, in load_extension
    raise exc.FrameworkError(e.args[0])
cement.core.exc.FrameworkError: No module named 'pylibmc'
```

I try to install the package with:
```
pip install pylibmc
```

And I get this error:

```
Collecting pylibmc
  Using cached pylibmc-1.5.1.tar.gz
Building wheels for collected packages: pylibmc
  Running setup.py bdist_wheel for pylibmc ... error
  Complete output from command /home/julen/Desktop/cement-example/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-64uommmi/pylibmc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpeyo9lfzopip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/pylibmc
  copying src/pylibmc/__init__.py -> build/lib.linux-x86_64-3.5/pylibmc
  copying src/pylibmc/consts.py -> build/lib.linux-x86_64-3.5/pylibmc
  copying src/pylibmc/test.py -> build/lib.linux-x86_64-3.5/pylibmc
  copying src/pylibmc/pools.py -> build/lib.linux-x86_64-3.5/pylibmc
  copying src/pylibmc/client.py -> build/lib.linux-x86_64-3.5/pylibmc
  copying src/pylibmc/__main__.py -> build/lib.linux-x86_64-3.5/pylibmc
  running build_ext
  building '_pylibmc' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_ZLIB -I/usr/include/python3.5m -I/home/julen/Desktop/cement-example/env/include/python3.5m -c src/_pylibmcmodule.c -o build/temp.linux-x86_64-3.5/src/_pylibmcmodule.o -fno-strict-aliasing -std=c99
  In file included from src/_pylibmcmodule.c:34:0:
  src/_pylibmcmodule.h:41:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pylibmc
  Running setup.py clean for pylibmc
Failed to build pylibmc
Installing collected packages: pylibmc
  Running setup.py install for pylibmc ... error
    Complete output from command /home/julen/Desktop/cement-example/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-64uommmi/pylibmc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s1o7fcwf-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/julen/Desktop/cement-example/env/include/site/python3.5/pylibmc:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pylibmc
    copying src/pylibmc/__init__.py -> build/lib.linux-x86_64-3.5/pylibmc
    copying src/pylibmc/consts.py -> build/lib.linux-x86_64-3.5/pylibmc
    copying src/pylibmc/test.py -> build/lib.linux-x86_64-3.5/pylibmc
    copying src/pylibmc/pools.py -> build/lib.linux-x86_64-3.5/pylibmc
    copying src/pylibmc/client.py -> build/lib.linux-x86_64-3.5/pylibmc
    copying src/pylibmc/__main__.py -> build/lib.linux-x86_64-3.5/pylibmc
    running build_ext
    building '_pylibmc' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_ZLIB -I/usr/include/python3.5m -I/home/julen/Desktop/cement-example/env/include/python3.5m -c src/_pylibmcmodule.c -o build/temp.linux-x86_64-3.5/src/_pylibmcmodule.o -fno-strict-aliasing -std=c99
    In file included from src/_pylibmcmodule.c:34:0:
    src/_pylibmcmodule.h:41:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/julen/Desktop/cement-example/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-64uommmi/pylibmc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s1o7fcwf-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/julen/Desktop/cement-example/env/include/site/python3.5/pylibmc" failed with error code 1 in /tmp/pip-build-64uommmi/pylibmc/
```

Sorry in advance if I'm making some kind of silly error; I'm almost new to Python development.

Thanks in advance and congrats for the successful work.

**Comment by akhilman** [comment]
Seems like this is memcached driver's problem, not cement's one.
In this particular example memcached actually not required and you can remove it from your extensions.
```python
# extensions = ['daemon', 'memcached', 'json', 'yaml']
extensions = ['daemon',  'json', 'yaml']
```

**Comment by derks** [comment]
@akhilman is right, this is just the fact that the example is using `memcached` extension which requires `pylibmc` as a dependency.  Probably not the best choice for an early "quickstart" example (sorry).  

The actual issue is that `pylibmc` requires Python development headers to build/install... as per the error you are getting:

```
fatal error: Python.h: No such file or directory
```

If you do want to get the `memcached` extension working, you need to install Python development package for your system which would allow you to `pip install pylibmc`.

**Comment by julenpardo** [comment]
@akhilman @derks Thanks for your quick answer,

you're both right, it's a problem with the extensions, and not Cement's itself.

Now that I know what's the problem, I can keep struggling with it, and this can be closed :) 

Thanks and keep up the great work.
