### ISSUE TITLE
Cannot import ABC from abc

### ISSUE THREAD

**Issue by KoRnZYSIEK** [datafolklabs/cement#528]
Hi,
I'm having problem installing cement - I'm getting error when installing requirment for abc on new host. The installation worked day before without issues.

**System Information**

- Cement Version: 3.0.0
- Python Version: 2.7.12
- Operating System and Version: Ubuntu 16.04

**Steps to Reproduce (Bugs Only)**

- Step 1 pip install cement

```Collecting cement
  Downloading https://files.pythonhosted.org/packages/fe/07/ab14a1a8a8e326b479ec76006e5d48f58cb058a2a9a6d70a373e463de1f4/cement-3.0.0.tar.gz (232kB)
    100% |████████████████████████████████| 235kB 730kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K8ennE/cement/setup.py", line 4, in <module>
        from cement.utils import version
      File "/tmp/pip-install-K8ennE/cement/cement/__init__.py", line 4, in <module>
        from .core.foundation import App, TestApp
      File "/tmp/pip-install-K8ennE/cement/cement/core/foundation.py", line 8, in <module>
        from ..core import exc, log, config, plugin
      File "/tmp/pip-install-K8ennE/cement/cement/core/log.py", line 8, in <module>
        from ..core.interface import Interface
      File "/tmp/pip-install-K8ennE/cement/cement/core/interface.py", line 5, in <module>
        from abc import ABC
    ImportError: cannot import name ABC```

**Comment by derks** [comment]
@KoRnZYSIEK Cement 3.0.0 explicitly does not support Python 2.  It is targeted, and tested for Python 3.5+.

**Comment by derks** [comment]
Sorry, should note that if you were previously using Cement, that you need to lock your version to `cement==2.10.2` as to not upgrade to Cement 3.0.

**Comment by derks** [comment]
@KoRnZYSIEK apologies, I mispoke.. the latest stable version of Cement 2 is `2.10.12`, so you would want `cement==2.10.12`.
