### ISSUE TITLE
Cement CLI Broken on Python 3.10

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#619]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/core/extension.py", line 124, in load_extension
    __import__(ext_module, globals(), locals(), [], 0)
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/ext/ext_jinja2.py", line 8, in <module>
    from jinja2 import Environment, FileSystemLoader, PackageLoader
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/cli/contrib/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/cli/contrib/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/cli/contrib/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/cli/contrib/jinja2/utils.py", line 647, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/cli/contrib/markupsafe/__init__.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cement", line 33, in <module>
    sys.exit(load_entry_point('cement==3.0.6', 'console_scripts', 'cement')())
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/cli/main.py", line 38, in main
    with CementApp() as app:
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/core/foundation.py", line 1677, in __enter__
    self.setup()
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/core/foundation.py", line 878, in setup
    self._setup_extension_handler()
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/core/foundation.py", line 1217, in _setup_extension_handler
    self.ext.load_extensions(self._meta.extensions)
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/core/extension.py", line 145, in load_extensions
    self.load_extension(ext)
  File "/usr/local/lib/python3.10/site-packages/cement-3.0.6-py3.10.egg/cement/core/extension.py", line 133, in load_extension
    raise exc.FrameworkError(e.args[0])
cement.core.exc.FrameworkError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

**Comment by derks** [comment]
Needs to change to `from collections.abc import Mapping` on Python >= 3.10, with backward compat.

**Comment by keinagae** [comment]
any update on this?

**Comment by derks** [comment]
Circling back to this finally. Cement library appears to run fine, and all tests pass on Cement 3.10... it is strictly with the command line tool, and included `contrib/markupsafe` library... oddly, running in 3.10 dev container doesn't trigger it, but running cement as the entrypoint (production Dockerfile) it does.

Reproduce:

- Modify `Dockerfile` to run on `python:3.10-alpine`
- Build image: `docker build -t cement:issue319`
- Run: ```docker run -it -v `pwd`:/data cement:issue319 generate project```
